import { logger } from "../../../utils/src/logger";

export type ModelProviderName = "codex" | "ollama" | "openai" | "custom";

export type RequirementAnalysis = {
  decision: "requirements_complete" | "requirements_gap" | "needs_clarification";
  summary: string;
  gapSummary?: string;
  commentToReporter?: string;
  confidence?: number;
};

export type ChangePlan = {
  decision: "proceed" | "requirements_gap" | "needs_clarification";
  summary: string;
  commitMessage: string;
  notes?: string;
  patch: string;
};

export type PatchRepairRequest = {
  issueKey: string;
  summary: string;
  requirementSummary: string;
  patchError: string;
  patch: string;
};

export type ModelProviderConfig = {
  provider: ModelProviderName;
  modelName: string;
  baseUrl?: string;
  apiKey?: string;
  temperature?: number;
  maxTokens?: number;
};

function parseJson<T>(value: string, fallback: T): T {
  try {
    return JSON.parse(value) as T;
  } catch {
    return fallback;
  }
}

export function normalizeJiraText(value: unknown): string {
  if (typeof value === "string") {
    return value;
  }
  if (value == null) {
    return "";
  }
  if (Array.isArray(value)) {
    return value.map((item) => normalizeJiraText(item)).filter(Boolean).join(" ");
  }
  if (typeof value === "object") {
    const doc = value as Record<string, unknown>;
    if (typeof doc.text === "string") {
      return doc.text;
    }
    if (typeof doc.body === "string") {
      return doc.body;
    }
    if (Array.isArray(doc.content)) {
      return doc.content.map((item) => normalizeJiraText(item)).filter(Boolean).join(" ");
    }
    return Object.values(doc)
      .map((item) => normalizeJiraText(item))
      .filter(Boolean)
      .join(" ");
  }
  return String(value);
}

function truncate(value: string, limit = 4000) {
  return value.length > limit ? `${value.slice(0, limit)}...<truncated>` : value;
}

function safePrompt(value: string) {
  return truncate(value.replace(/Authorization:\s*Basic\s+[^\s]+/gi, "Authorization: Basic [redacted]"));
}

export interface ModelProvider {
  testConnection(): Promise<{ ok: true; message: string }>;
  analyzeRequirement(input: {
    issueKey: string;
    summary: string;
    description?: string;
    comments?: string[];
  }): Promise<RequirementAnalysis>;
  generateImplementationPlan(input: {
    issueKey: string;
    summary: string;
    requirement: RequirementAnalysis;
  }): Promise<ChangePlan>;
  repairPatch(input: PatchRepairRequest): Promise<ChangePlan>;
}

class BaseProvider implements ModelProvider {
  constructor(protected readonly config: ModelProviderConfig) {}

  async testConnection() {
    return {
      ok: true as const,
      message: `Provider ${this.config.provider}:${this.config.modelName} is ready`
    };
  }

  protected logPrompt(stage: string, prompt: string) {
    logger.info("model prompt", {
      provider: this.config.provider,
      modelName: this.config.modelName,
      stage,
      prompt: safePrompt(prompt)
    });
  }

  protected logReply(stage: string, reply: unknown) {
    const serialized = typeof reply === "string" ? reply : JSON.stringify(reply);
    logger.info("model reply", {
      provider: this.config.provider,
      modelName: this.config.modelName,
      stage,
      reply: truncate(serialized)
    });
  }

  async analyzeRequirement(input: {
    issueKey: string;
    summary: string;
    description?: string;
    comments?: string[];
  }): Promise<RequirementAnalysis> {
    const description = normalizeJiraText(input.description).trim();
    const hasDescription = Boolean(description);
    if (!hasDescription) {
      return {
        decision: "needs_clarification",
        summary: `Issue ${input.issueKey} needs clarification`,
        gapSummary: "Jira description is missing or empty",
        commentToReporter: `Hi I am etBek: ${input.issueKey}\nI need a Jira description with the expected behavior, scope, and examples before I can implement this.`,
        confidence: 0.95
      };
    }

    return {
      decision: "requirements_complete",
      summary: `Requirement for ${input.issueKey} looks actionable`,
      confidence: 0.7
    };
  }

  async generateImplementationPlan(input: {
    issueKey: string;
    summary: string;
    requirement: RequirementAnalysis;
  }): Promise<ChangePlan> {
    return {
      decision: "proceed",
      summary: `No-op implementation plan for ${input.issueKey}`,
      commitMessage: `feat(${input.issueKey}): implement Jira requirement`,
      notes: `Plan generated by ${this.config.provider}:${this.config.modelName}`,
      patch: ""
    };
  }

  async repairPatch(input: PatchRepairRequest): Promise<ChangePlan> {
    return {
      decision: "proceed",
      summary: `Patch repair not available for ${input.issueKey}`,
      commitMessage: `feat(${input.issueKey}): implement Jira requirement`,
      notes: `Patch repair skipped for ${this.config.provider}:${this.config.modelName}`,
      patch: input.patch
    };
  }
}

class OllamaProvider extends BaseProvider {
  async testConnection() {
    const baseUrl = this.config.baseUrl ?? "http://localhost:11434";
    const response = await fetch(`${baseUrl}/api/tags`, { method: "GET" });
    if (!response.ok) {
      throw new Error(`Ollama connection failed with HTTP ${response.status}`);
    }
    return {
      ok: true as const,
      message: `Ollama reachable at ${baseUrl}`
    };
  }

  async analyzeRequirement(input: {
    issueKey: string;
    summary: string;
    description?: string;
    comments?: string[];
  }): Promise<RequirementAnalysis> {
    const baseUrl = this.config.baseUrl ?? "http://localhost:11434";
    const prompt = `Return JSON only with keys decision, summary, gapSummary, commentToReporter, confidence. Issue: ${input.issueKey}. Summary: ${input.summary}. Description: ${input.description ?? ""}. Comments: ${(input.comments ?? []).join("\n")}`;
    this.logPrompt("analyze_requirement", prompt);
    const response = await fetch(`${baseUrl}/api/generate`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: this.config.modelName,
        prompt,
        stream: false,
        options: {
          temperature: this.config.temperature ?? 0.2,
          num_predict: this.config.maxTokens ?? 1024
        }
      })
    });
    if (!response.ok) {
      return super.analyzeRequirement(input);
    }
    const payload = (await response.json()) as { response?: string };
    this.logReply("analyze_requirement", payload.response ?? "");
    return parseJson<RequirementAnalysis>(
      payload.response ?? "",
      await super.analyzeRequirement(input)
    );
  }

  async generateImplementationPlan(input: {
    issueKey: string;
    summary: string;
    requirement: RequirementAnalysis;
  }): Promise<ChangePlan> {
    const baseUrl = this.config.baseUrl ?? "http://localhost:11434";
    const prompt = [
      "Return JSON only with keys decision, summary, commitMessage, notes, patch.",
      "The patch must be a valid unified diff or empty string.",
      `Issue: ${input.issueKey}`,
      `Summary: ${input.summary}`,
      `Requirement decision: ${input.requirement.decision}`,
      `Requirement summary: ${input.requirement.summary}`,
      `Gap summary: ${input.requirement.gapSummary ?? ""}`
    ].join("\n");
    this.logPrompt("generate_plan", prompt);
    const response = await fetch(`${baseUrl}/api/generate`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: this.config.modelName,
        prompt,
        stream: false,
        options: {
          temperature: this.config.temperature ?? 0.2,
          num_predict: this.config.maxTokens ?? 2048
        }
      })
    });
    if (!response.ok) {
      return super.generateImplementationPlan(input);
    }
    const payload = (await response.json()) as { response?: string };
    this.logReply("generate_plan", payload.response ?? "");
    return parseJson<ChangePlan>(
      payload.response ?? "",
      await super.generateImplementationPlan(input)
    );
  }

  async repairPatch(input: PatchRepairRequest): Promise<ChangePlan> {
    const baseUrl = this.config.baseUrl ?? "http://localhost:11434";
    const prompt = [
      "Return JSON only with keys decision, summary, commitMessage, notes, patch.",
      "Fix the provided patch so it becomes a valid unified diff.",
      `Issue: ${input.issueKey}`,
      `Summary: ${input.summary}`,
      `Requirement summary: ${input.requirementSummary}`,
      `Patch error: ${input.patchError}`,
      `Patch to repair:\n${input.patch}`
    ].join("\n");
    this.logPrompt("repair_patch", prompt);
    const response = await fetch(`${baseUrl}/api/generate`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: this.config.modelName,
        prompt,
        stream: false,
        options: {
          temperature: this.config.temperature ?? 0.2,
          num_predict: this.config.maxTokens ?? 2048
        }
      })
    });
    if (!response.ok) {
      return super.repairPatch(input);
    }
    const payload = (await response.json()) as { response?: string };
    this.logReply("repair_patch", payload.response ?? "");
    return parseJson<ChangePlan>(
      payload.response ?? "",
      await super.repairPatch(input)
    );
  }
}

class CodexProvider extends BaseProvider {}

export function createModelProvider(config: ModelProviderConfig): ModelProvider {
  switch (config.provider) {
    case "ollama":
      return new OllamaProvider(config);
    case "codex":
      return new CodexProvider(config);
    default:
      return new BaseProvider(config);
  }
}
